version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cards-sam-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-11tw0re4skmt5"
s3_prefix = "cards-sam-app"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
